export default {
  SENDGRID_ENQUIRY_SENDER: process.env.SENDGRID_ENQUIRY_SENDER,

  SENDGRID_BILLING_SENDER: process.env.SENDGRID_BILLING_SENDER,

  SENDGRID_DISPUTE_SENDER: process.env.SENDGRID_DISPUTE_SENDER,

  EMAIL_SENDER_NAME: process.env.EMAIL_SENDER_NAME,

  TYPE: {
    DISPUTE: 'DISPUTE',

    BILLING: 'BILLING',

    ENQUIRY: 'ENQUIRY'
  }
};
