export default {
  SENDGRID_ENQUIRY_SENDER: process.env.SENDGRID_ENQUIRY_SENDER,

  SENDGRID_BILLING_SENDER: process.env.SENDGRID_BILLING_SENDER,

  SENDGRID_DISPUTE_SENDER: process.env.SENDGRID_DISPUTE_SENDER,

  SENDGRID_SUPPORT_SENDER: process.env.SENDGRID_SUPPORT_SENDER,

  EMAIL_SENDER_NAME: process.env.EMAIL_SENDER_NAME,

  ADMIN_EMAIL: process.env.ADMIN_EMAIL,

  TYPE: {
    DISPUTE: 'DISPUTE',

    BILLING: 'BILLING',

    ENQUIRY: 'ENQUIRY',

    SUPPORT: 'SUPPORT'
  }
};
