export const SEARCH_TYPES = {
  MATCH: 1,
  LIKE: 2
};

export const USER_TYPE = {
  ADMIN: 1,
  CUSTOMER: 2,
  SELLER: 3
};

export const COURIER = {
  POSTLAJU: 'POSTLAJU'
};

export const PAYMENT_METHOD = {
  ONLINE_BANKING: 'ONLINE_BANKING',
  CASH_DEPOSIT: 'CASH_DEPOSIT',
  CREDIT_DEBIT_CARD: 'CREDIT_DEBIT_CARD'
};

export const PAYMENT_STATUS = {
  SUCCESS: 'SUCCESS',
  PENDING: 'PENDING',
  FAILED: 'FAILED'
};

export const DELIVERY_STATUS = {
  PAID: 'PAID',
  SHIPPED: 'SHIPPED',
  STATUS: 'STATUS'
};
